### ISSUE TITLE
keepass2 import fails when line breaks present in password

### ISSUE THREAD

**Issue by vectorsize** [buttercup-pw/buttercup-importer#6]
So I store some software keys on my keepass and they contain line breaks in the password, but when trying to import them into buttercup the buttercup-importer keepass2importer fails when it encounters those characters.

I attach a simple database with one password containing the problematic character.

[buttercup-import-test.kdbx.zip](https://github.com/buttercup-pw/buttercup-importer/files/833305/buttercup-import-test.kdbx.zip)

The database's password is `bc`

**Comment by vectorsize** [comment]
for reference, code breaks [here](https://github.com/buttercup-pw/buttercup-importer/blob/master/source/importers/KeePass2Importer.js#L47)

**Comment by perry-mitchell** [comment]
Thanks a lot for looking into this, we'll take a look shortly!

**Comment by perry-mitchell** [comment]
Hmm.. this may be due to the way we store history (entry properties). It probably doesn't handle new lines so well.. This could be a breaking change.

**Comment by vectorsize** [comment]
thank you!! perhaps serializing-deserializing? idk the details…

**Comment by perry-mitchell** [comment]
> serializing-deserializing

Yes, we definitely overlooked that. It should be that we perhaps base64 encode the values first so that we don't corrupt archives with newlines..

**Comment by perry-mitchell** [comment]
This is blocked by buttercup-pw/buttercup-core#143

**Comment by perry-mitchell** [comment]
The work is done - should be fixed by updating buttercup core to 0.35.0.

**Comment by perry-mitchell** [comment]
Sorry @vectorsize - We need to patch it in this repo and then in the butterup GUI (buttercup-pw/buttercup) (requires both buttercup-importer and buttercup-core-web): buttercup-pw/buttercup#171. It should be done today or tomorrow.

Of course you could make an MR here to help speed up the process, but I suspect that the importer is the simpler part :)

**Comment by vectorsize** [comment]
All right, I thought I could try it right away... I' not in a hurry, and have other stuff on my plate this week, so I can't help much right now, I'll wait for it to be released :) thanks again!

**Comment by perry-mitchell** [comment]
@vectorsize I've published the fix in 0.7.0, so that should work for you now. I'll be integrating this into Buttercup GUI soon - unfortunately archives imported in this version will not yet work there until it's updated.

**Comment by perry-mitchell** [comment]
@vectorsize Thanks again! The new release of the GUI is here: https://github.com/buttercup-pw/buttercup/releases/tag/v0.10.1-alpha

All current versions should not be serialising their properties.

**Comment by vectorsize** [comment]
Great news, thanks a bunch and again great job!! Will try this soon and report if something doesn't go as expected! 🤓✌️

**Comment by vectorsize** [comment]
![image](https://cloud.githubusercontent.com/assets/1661889/24033455/3c1291c6-0aed-11e7-955f-e5a160c4de0c.png)

Really sorry to say… strangely enough trying to import again a simple db with 2 passwords one of them with a line-break in the password and still doesn't work, is it possible there is some caching or something didn't refresh a dependency version?

**Comment by perry-mitchell** [comment]
@vectorsize What version of the UI are you using? It should say "0.10.1" on the main page.

If you running the dev version, make sure to npm install. You could also check that the buttercup-importer module is at 0.7.0.

**Comment by vectorsize** [comment]
![image](https://cloud.githubusercontent.com/assets/1661889/24038175/8cdc472e-0b00-11e7-8e68-9e17183613d3.png)

**Comment by perry-mitchell** [comment]
Ok, seems I can still reproduce the issue.. Dang:

![image](https://cloud.githubusercontent.com/assets/3869469/24038253/51d860a0-0b09-11e7-920d-d7456acd9e58.png)

Sorry @vectorsize - We'll try again. Maybe we missed the version somehow.

**Comment by vectorsize** [comment]
💩

**Comment by perry-mitchell** [comment]
Ok, new release coming shortly, sorry.
